extends SceneTree
## Sprite Forge roster importer (docs/12 §2.14): copies the lab-roster
## sheets plus a roster-filtered manifest from the gdignored raw drop
## (assets/spriteforge/) into the project-visible spriteforge/ dir, where
## Godot imports the PNGs. Manifest-driven: only actors named in
## data/actor_sheet_map.tres move — the pack's remaining actors stay
## untouched by the lab (scope tripwire). Re-run after editing the map,
## then run `godot --headless --path . --import`.
##
## Usage: godot --headless --path . --script addons/spriteforge_importer/import_roster.gd

const SRC_ROOT := "res://assets/spriteforge/"
const DST_ROOT := "res://spriteforge/"


func _init() -> void:
	var sheet_map: Resource = load("res://data/actor_sheet_map.tres")
	if sheet_map == null:
		push_error("import_roster: data/actor_sheet_map.tres missing")
		quit(1)
		return
	var ids: Array[String] = []
	for role: String in sheet_map.map:
		var id := String(sheet_map.map[role])
		if not ids.has(id):
			ids.append(id)
	ids.sort()

	var manifest: Variant = JSON.parse_string(
		FileAccess.get_file_as_string(SRC_ROOT + "manifest.json")
	)
	if manifest == null:
		push_error("import_roster: cannot read %smanifest.json" % SRC_ROOT)
		quit(1)
		return

	var picked: Array[Dictionary] = []
	for entry: Dictionary in manifest.actors:
		if ids.has(String(entry.id)):
			picked.append(entry)
	if picked.size() != ids.size():
		var found: Array[String] = []
		for entry: Dictionary in picked:
			found.append(String(entry.id))
		push_error(
			(
				"import_roster: roster ids missing from pack manifest: %s"
				% str(ids.filter(func(i: String) -> bool: return not found.has(i)))
			)
		)
		quit(1)
		return

	var out := {}
	for key: String in manifest:
		if key != "actors" and key != "counts":
			out[key] = manifest[key]
	out["roster_note"] = "Roster-filtered copy generated by import_roster.gd; the full pack manifest lives in assets/spriteforge/ (gdignored). Regenerate, never hand-edit."
	out["actors"] = picked

	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(DST_ROOT))
	for entry: Dictionary in picked:
		var sheet := String(entry.sheet)
		var dst := DST_ROOT + sheet
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(dst.get_base_dir()))
		var bytes := FileAccess.get_file_as_bytes(SRC_ROOT + sheet)
		if bytes.is_empty():
			push_error("import_roster: sheet missing or empty: %s" % sheet)
			quit(1)
			return
		var f := FileAccess.open(dst, FileAccess.WRITE)
		f.store_buffer(bytes)
		f.close()
		print("import_roster: %s (%d bytes)" % [sheet, bytes.size()])

	var mf := FileAccess.open(DST_ROOT + "manifest.json", FileAccess.WRITE)
	mf.store_string(JSON.stringify(out, "\t"))
	mf.close()
	print("import_roster: %d actors -> %smanifest.json" % [picked.size(), DST_ROOT])
	quit(0)
